### ISSUE TITLE
Support for Windows 8.1 x64

### ISSUE THREAD

**Issue by betonme** [nitsch/psmove-pair-win#1]
I tried the pairing with Windows 8.1 x64, without success

Here is the program output:

==== Looking for Bluetooth radios ====
(0)  xxxx  PC

Using the only available Bluetooth radio.
Making radio accept incoming connections.
Making radio discoverable.

==== Connecting new controllers ====
(0)  yyyy  Motion Controller
CoD: 0x00002508, CON: 0, REM: 0, AUTH: 0

device #0: Move Motion Controller detected
(0)  yyyy  Motion Controller
CoD: 0x00002508, CON: 1, REM: 0, AUTH: 0

device #0: Move Motion Controller detected
- checking HID service
- enabling HID service
- verifying successful connection

(0)  yyyy  Motion Controller
CoD: 0x00002508, CON: 0, REM: 1, AUTH: 0

After that the led of the motion controller continoues blinking and goes off.

I tried it several times

**Comment by betonme** [comment]
Do You know a working connection procedure for Windows 8.1 x64?

Thank You

**Comment by nitsch** [comment]
> Do You know a working connection procedure for Windows 8.1 x64?

I do not have Windows 8 available for testing, but there was some
successful registry hacking described on the PS Move API mailing list
for that version of Windows:

  https://groups.google.com/d/topic/psmove/TOJlZ_siXSQ

**Comment by nitsch** [comment]
The procedure from the mailing list along with some more tweaks went into the branch [win8-support](https://github.com/nitsch/psmove-pair-win/tree/win8-support). It seems to work pretty well on Windows 8.1.
